# Generated by Django 5.1 on 2024-08-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'CHUM Inventory'},
        ),
    ]
