# Generated by Django 5.1 on 2024-08-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
